# Generated by Django 4.1.2 on 2022-11-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trains", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trains",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="trains",
            name="renovation_at",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="trains",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
    ]
