# Generated by Django 4.1.2 on 2022-11-02 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0001_initial"),
        ("modalities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modality",
            name="teachers",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modality",
                to="teachers.teacher",
            ),
            preserve_default=False,
        ),
    ]
