# Generated by Django 4.1.2 on 2022-11-03 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0001_initial"),
        ("modalities", "0003_rename_teachers_modality_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modality",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modalities",
                to="teachers.teacher",
            ),
        ),
    ]
