# Generated by Django 4.1.2 on 2022-11-03 13:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="schedule",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20),
                default=["Segunda", "Terça"],
                size=None,
            ),
            preserve_default=False,
        ),
    ]
