# Generated by Django 4.1.2 on 2022-11-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("classes", "0003_rename_capacity_class_max_capacity_class_customers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="customers",
            field=models.ManyToManyField(
                related_name="classes", to="customers.customer"
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="max_capacity",
            field=models.PositiveIntegerField(),
        ),
    ]
