# Generated by Django 4.1.2 on 2022-11-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="tier",
            field=models.CharField(
                choices=[
                    ("Bronze", "Bronze"),
                    ("Prata", "Prata"),
                    ("Ouro", "Ouro"),
                    ("Não informado", "Default"),
                ],
                max_length=255,
            ),
        ),
    ]
