# Generated by Django 4.1.2 on 2022-11-01 19:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Private_training",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("hour", models.TimeField()),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("customer_id", models.CharField(max_length=200)),
                ("personal_id", models.CharField(max_length=200)),
            ],
        ),
    ]
