# Generated by Django 4.1.2 on 2022-11-07 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("personals", "0002_initial"),
        ("customers", "0002_initial"),
        ("private_trainings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="private_training",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="private_trainings",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="private_training",
            name="personal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="private_trainings",
                to="personals.personal",
            ),
        ),
    ]
